FROM debian:10

ARG USER_NAME
ARG USER_ID
ARG USER_GROUP_ID

ARG DEBIAN_FRONTEND=noninteractive

ENV USER_NAME=${USER_NAME} \
    USER_ID=${USER_ID} \
    USER_GROUP_ID=${USER_GROUP_ID} \
    OS_NAME=deb10

RUN echo ">>> USER_NAME=${USER_NAME}" \
 && echo ">>> USER_ID=${USER_ID}" \
 && echo ">>> USER_GROUP_ID=${USER_GROUP_ID}"

RUN sed -i -e 's/deb.debian.org/archive.debian.org/g' \
           -e 's|security.debian.org|archive.debian.org/|g' \
           -e '/buster-updates/d' /etc/apt/sources.list

RUN cp /etc/apt/sources.list /etc/apt/sources.list~ \
  && echo 'deb-src http://archive.debian.org/debian buster main' >> /etc/apt/sources.list \
  && apt-get update \
  && apt-get install -y --no-install-recommends git openssl apt-utils software-properties-common build-essential gcc g++ wget libssl-dev liblog4cpp5-dev libarchive-dev libeigen3-dev libgdal-dev libkml-dev locate zip unzip qtchooser chrpath libtbb-dev libgeos-dev libx11-dev libxcb1-dev libxkbcommon-dev libgles2-mesa-dev libegl1-mesa-dev libxrender-dev libxcb-xinerama0-dev libxcb-image0-dev libwayland-dev gedit libgl1-mesa-dev libxkbcommon-x11-dev qt5-* libqt5* qtwayland5 libgif-dev libjpeg-dev libgeos++-dev autoconf automake libtool curl libglew-dev libzip-dev libpcap-dev libgeographic-dev python2.7-dev libfreetype6-dev libfontconfig1-dev patchelf sudo xvfb xauth mesa-utils \
  && apt-get build-dep -y libopenscenegraph-dev libosgearth-dev libboost-all-dev \
  && rm -rf /var/lib/apt/lists/*

RUN apt-get update && \
    apt-get remove --purge -y libopenscenegraph-3.4-131 && \
    apt-get autoremove -y && \
    rm -rf /usr/lib/x86_64-linux-gnu/osgPlugins-3.4.1  
  
RUN groupadd -r someusers --gid=${USER_GROUP_ID} 
RUN useradd -r -p "$(openssl passwd -1 ${USER_NAME})" -g someusers -G sudo --uid=${USER_ID} --create-home --shell /bin/bash ${USER_NAME} 

ENV CXXFLAGS="-march=x86-64 -mtune=generic"
ENV CFLAGS="-march=x86-64 -mtune=generic"

#install cmake

ENV CMAKE_VERSION=3.28
ENV CMAKE_BUILD=1

RUN wget https://cmake.org/files/v${CMAKE_VERSION}/cmake-${CMAKE_VERSION}.${CMAKE_BUILD}.tar.gz
RUN tar xzvf cmake-${CMAKE_VERSION}.${CMAKE_BUILD}.tar.gz
RUN cd cmake-${CMAKE_VERSION}.${CMAKE_BUILD}/ && ./bootstrap
RUN cd cmake-${CMAKE_VERSION}.${CMAKE_BUILD}/ && make -j$(nproc)
RUN cd cmake-${CMAKE_VERSION}.${CMAKE_BUILD}/ && make install
RUN cmake --version

#install boost

RUN wget -O boost_1_83_0.tar.gz https://sourceforge.net/projects/boost/files/boost/1.83.0/boost_1_83_0.tar.gz/download --no-check-certificate
RUN tar xzvf boost_1_83_0.tar.gz
RUN cd boost_1_83_0/ && ./bootstrap.sh --prefix=/usr/local/
RUN cd boost_1_83_0/ && ./b2 headers cxxflags="-std=c++17 -march=x86-64 -mtune=generic"
RUN cd boost_1_83_0/ && ./b2 install cxxflags="-std=c++17 -march=x86-64 -mtune=generic"

RUN git clone --branch OpenSceneGraph-3.6 --depth 1 https://github.com/openscenegraph/OpenSceneGraph.git OpenSceneGraph-3.6
RUN mkdir OpenSceneGraph-3.6/build
RUN cd OpenSceneGraph-3.6/build && cmake \
    -DBUILD_SHARED_LIBS=ON \
    -DCMAKE_INSTALL_PREFIX=/usr \
    -DCMAKE_BUILD_TYPE=Release \
    -DCMAKE_CXX_FLAGS="-DGL_COMPRESSED_SRGB_S3TC_DXT1_EXT=0x8C4C -DGL_COMPRESSED_SRGB_ALPHA_S3TC_DXT1_EXT=0x8C4D -DGL_COMPRESSED_SRGB_ALPHA_S3TC_DXT3_EXT=0x8C4E -DGL_COMPRESSED_SRGB_ALPHA_S3TC_DXT5_EXT=0x8C4F" \
    -DOPENGL_PROFILE=GLCORE \
    -DOSG_GLU_AVAILABLE=OFF \
    -DOSG_GL1_AVAILABLE=OFF \
    -DOSG_GL2_AVAILABLE=OFF \
    -DOSG_GL3_AVAILABLE=ON \
    -DOSG_GLES1_AVAILABLE=OFF \
    -DOSG_GLES2_AVAILABLE=OFF \
    -DOSG_GL_DISPLAYLISTS_AVAILABLE=OFF \
    -DOSG_GL_MATRICES_AVAILABLE=OFF \
    -DOSG_GL_VERTEX_FUNCS_AVAILABLE=OFF \
    -DOSG_GL_VERTEX_ARRAY_FUNCS_AVAILABLE=OFF \
    -DOSG_GL_FIXED_FUNCTION_AVAILABLE=OFF \
    ..
RUN cd OpenSceneGraph-3.6/build && make -j$(nproc)
RUN cd OpenSceneGraph-3.6/build && make install

RUN rm -rf OpenSceneGraph-3.6/build/lib

#RUN wget https://github.com/openscenegraph/osgQt/archive/Qt4.zip
#RUN unzip Qt4.zip
#RUN mkdir osgQt-Qt4/build
#RUN cd osgQt-Qt4/build && cmake -DCMAKE_INSTALL_PREFIX=/usr -DCMAKE_BUILD_TYPE=Release ..
#RUN cd osgQt-Qt4/build && make -j$(nproc)
#RUN cd osgQt-Qt4/build && make install

RUN wget https://github.com/protocolbuffers/protobuf/releases/download/v3.19.1/protobuf-cpp-3.19.1.zip
RUN unzip protobuf-cpp-3.19.1.zip
RUN cd protobuf-3.19.1 && ./autogen.sh
RUN cd protobuf-3.19.1 && ./configure
RUN cd protobuf-3.19.1 && make -j$(nproc)
#RUN cd protobuf-3.19.1 && make check
RUN cd protobuf-3.19.1 && make install
RUN cd protobuf-3.19.1 && ldconfig # refresh shared library cache.

# Create CMake config for GEOS so osgEarth's find_package(geos) succeeds
# Debian 10's libgeos-dev does not ship CMake config files
RUN mkdir -p /usr/lib/x86_64-linux-gnu/cmake/geos && \
    echo 'add_library(GEOS::geos_c SHARED IMPORTED)' > /usr/lib/x86_64-linux-gnu/cmake/geos/geos-config.cmake && \
    echo 'set_target_properties(GEOS::geos_c PROPERTIES' >> /usr/lib/x86_64-linux-gnu/cmake/geos/geos-config.cmake && \
    echo '  IMPORTED_LOCATION "/usr/lib/x86_64-linux-gnu/libgeos_c.so"' >> /usr/lib/x86_64-linux-gnu/cmake/geos/geos-config.cmake && \
    echo '  INTERFACE_INCLUDE_DIRECTORIES "/usr/include"' >> /usr/lib/x86_64-linux-gnu/cmake/geos/geos-config.cmake && \
    echo ')' >> /usr/lib/x86_64-linux-gnu/cmake/geos/geos-config.cmake

# Create CMake config for libzip so osgEarth's find_package(libzip) succeeds
# Debian 10's libzip-dev does not ship CMake config files
RUN mkdir -p /usr/lib/x86_64-linux-gnu/cmake/libzip && \
    echo 'add_library(libzip::zip SHARED IMPORTED)' > /usr/lib/x86_64-linux-gnu/cmake/libzip/libzip-config.cmake && \
    echo 'set_target_properties(libzip::zip PROPERTIES' >> /usr/lib/x86_64-linux-gnu/cmake/libzip/libzip-config.cmake && \
    echo '  IMPORTED_LOCATION "/usr/lib/x86_64-linux-gnu/libzip.so"' >> /usr/lib/x86_64-linux-gnu/cmake/libzip/libzip-config.cmake && \
    echo '  INTERFACE_INCLUDE_DIRECTORIES "/usr/include"' >> /usr/lib/x86_64-linux-gnu/cmake/libzip/libzip-config.cmake && \
    echo ')' >> /usr/lib/x86_64-linux-gnu/cmake/libzip/libzip-config.cmake

RUN git clone --branch osgearth-3.8 --depth 1 --recurse-submodules https://github.com/gwaldron/osgearth.git osgearth-3.8
RUN mkdir osgearth-3.8/build
RUN cd osgearth-3.8/build && cmake -DOSGEARTH_BUILD_TESTS=OFF -DOSGEARTH_BUILD_EXAMPLES=OFF -DBUILD_SHARED_LIBS=ON -DCMAKE_INSTALL_PREFIX=/usr -DCMAKE_INSTALL_LIBDIR=lib -DCMAKE_BUILD_TYPE=Release ..
RUN cd osgearth-3.8/build && make -j$(nproc)
RUN cd osgearth-3.8/build && make install

RUN wget https://github.com/hpuhr/NemaTode/archive/refs/heads/master.zip
RUN unzip master.zip
RUN mkdir NemaTode-master/build
RUN cd NemaTode-master/build && cmake -DCMAKE_INSTALL_PREFIX=/usr -DCMAKE_BUILD_TYPE=Release ..
RUN cd NemaTode-master/build && make -j$(nproc)
RUN cd NemaTode-master/build && make install

RUN wget https://github.com/duckdb/duckdb/releases/download/v1.5.2/libduckdb-linux-amd64.zip
RUN mkdir libduckdb-linux-amd64
RUN unzip libduckdb-linux-amd64.zip -d libduckdb-linux-amd64
RUN cd libduckdb-linux-amd64 && cp *.h /usr/include
RUN cd libduckdb-linux-amd64 && cp lib* /usr/lib

# Download and Install DuckDB CLI Client
RUN wget https://github.com/duckdb/duckdb/releases/download/v1.5.2/duckdb_cli-linux-amd64.zip
RUN unzip duckdb_cli-linux-amd64.zip -d libduckdb-linux-amd64
RUN mv libduckdb-linux-amd64/duckdb /usr/bin/
RUN chmod +x /usr/bin/duckdb

# Verify that the JSON extension is available and functional
RUN duckdb -c "INSTALL json; LOAD json; SELECT json_object('status', 'success') AS json_check;"

RUN ldconfig -v /usr/lib64/ /usr/local/
RUN updatedb

RUN echo "${USER_NAME} ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers
RUN more /etc/sudoers

# Verify Xvfb + software OpenGL core profile (3.3 needed for OSG GL3 build)
RUN xvfb-run -a glxinfo | grep -E "OpenGL (core profile |)(renderer|version|shading language version)"

USER ${USER_NAME}
WORKDIR /app/workspace/compass/docker
