when:
  - event: [push, manual]

steps:
  - name: setup-workspace
    image: alpine/git
    secrets:
      - github_token
    commands:
      - git clone --depth 1 --branch ${CI_COMMIT_BRANCH} https://$${GITHUB_TOKEN}@github.com/hpuhr/experimental_src.git experimental_src || git clone --depth 1 --branch devel https://$${GITHUB_TOKEN}@github.com/hpuhr/experimental_src.git experimental_src
      - git clone --depth 1 --branch devel https://github.com/hpuhr/jASTERIX.git ../jasterix

  - name: build
    image: compass/build_deb10
    commands:
      - sudo mkdir -p /app/workspace
      - sudo mv "$CI_WORKSPACE/../jasterix" /app/workspace/jasterix
      - sudo mv "$CI_WORKSPACE" /app/workspace/compass
      - sudo chown -R $(id -u):$(id -g) /app/workspace
      - cd /app/workspace/compass/docker && ./build_jasterix.sh && ./build_compass.sh
      - sudo mv /app/workspace/compass "$CI_WORKSPACE"

  - name: test
    image: compass/build_deb10
    commands:
      - ./build_deb10/bin/compass_tests

  - name: appimage
    image: compass/build_deb10
    commands:
      - sudo mkdir -p /app/workspace
      - sudo mv "$CI_WORKSPACE/../jasterix" /app/workspace/jasterix
      - sudo mv "$CI_WORKSPACE" /app/workspace/compass
      - sudo chown -R $(id -u):$(id -g) /app/workspace
      - cd /app/workspace/compass/docker && ./deploy_compass.sh
      - sudo mv /app/workspace/compass "$CI_WORKSPACE"
